kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: investup
spec:
  replicas: 1
  template:
    metadata:
      name: investup
      labels:
        app: investup-web
        role: admin
        env: production
    spec:
      containers:
      - name: investup
        image: gcr.io/th-ekramhassen/gceme:1.0.0
        env:
          - name: NODE_ENV
            value: production
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        ports:
        - name: investup
          containerPort: 3000
